name: install-test-ansible

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "9.3.0"

      - name: "Print Ansible version"
        run: ansible-playbook --version
